#Loading assignments and demos

If using Google Colab (Recommended)
1. Go to your personal Google Drive
2. Click "+ New" -> "More"
3. If you see Google Colaboratory, skip (4-6)
4. Click "+ Connect more apps"
5. Search for Colaboratory
6. Install Colaboratory
7. In your Drive, create a folder named ```csed501```
8. In ```csed501```, create a folder called ```demos```
9. Download the zip file for this demo from Canvas
10. Unzip the demo into a folder named ```demo1```
11. Upload the file for this demo into your ```demos``` folder.
12. Open the week_1_demo.ipynb file using Google Colab.
13. Modify the code below (replacing ```FOLDERNAME``` with the name of your ```demos``` folder) and run. Follow the resulting pop-ups to allow the code to run, and permit the notebook to access your Google Drive files

If using Kaggle Notebooks
1. Download the zip file for this assignment from Canvas
2. Unzip the assignment into a folder named ```demo1```
3. In Kaggle Notebook, go to "File" -> "Import Notebook" and upload ```demo1.ipynb```

In [ ]:
# This mounts your Google Drive to the Colab VM.
from google.colab import drive
drive.mount('/content/drive')

# TODO: Enter the foldername in your Drive where you have saved the unzipped
# assignment folder, e.g. 'csed501/demos/demo1/'
FOLDERNAME = 'csed501/demos/demo1/'
assert FOLDERNAME is not None, "[!] Enter the foldername."

# Now that we've mounted your Drive, this ensures that
# the Python interpreter of the Colab VM can load
# python files from within it.
import sys
sys.path.append('/content/drive/My Drive/{}'.format(FOLDERNAME))

Mounted at /content/drive


**IMPORTANT Note: Ensure you are periodically saving your notebook (File -> Save) so that you don't lose your progress if you step away from the assignment and the Colab VM disconnects.**

Google Colab lets us run Python code online, and will give access to cloud computing/GPUs in future courses. We'll use this demo to run through some Python and Numpy info, but you should do Assignment 0 and the associated tutorials if needed; this is simply a whirlwind tour.

For this and future assignments, if you are working in Google Colab, we strongly recommend navigating to Tools -> Settings -> AI Assistance and unchecking the "Show AI-powered inline completions" box. This will remove AI suggestions for your coding answers, and will help you focus on understanding the necessary concepts for this and future courses.

Each code block can be run by pressing the arrow on the top left side. If you run one code block after another, all variables, imports, etc. will still be saved, as if it was all in one file. Be careful to run code blocks in the desired order.

#Very quick Python tour

Modified from Hunter Schafer (CSE 416).

**Variable types**
Typing in Python is optional, not the convention. The interpreter will automatically type variables.

In [ ]:
# This is a comment
"""
This is a multiple line comment
"""


a:int = 5
b:float = 2.0
c:str = 'hello'
my_greeting:str= "hello"
e:bool = True
f:None = None

print("a = " + str(a))
print("b = " + str(b))
print("c = " + str(c))
print("my_greeting = " + str(my_greeting))
print("e = " + str(e))
print("f = " + str(f))

print("--------------------")

a1 = 5 #still an int
b1 = 2.0 #still a float
c1 = 'hello' #still a str
my_greeting_1= "hello" #still a str
e1 = True #still a bool
f1 = None #still None

print("a1 = " + str(a1))
print("b1 = " + str(b1))
print("c1 = " + str(c1))
print("my_greeting_1 = " + str(my_greeting_1))
print("e1 = " + str(e1))
print("f1 = " + str(f1))

a = 5
b = 2.0
c = hello
my_greeting = hello
e = True
f = None
--------------------
a1 = 5
b1 = 2.0
c1 = hello
my_greeting_1 = hello
e1 = True
f1 = None


The type of a variable is not fixed. In the following example, we assigned the variable x to 5, which is an int type. We later assigned it to "CSED501" , which is a str type.

In [ ]:
x = 5
print(x)
x = "CSED501"
print(x)

**Python operators** Python has some basic operators.

In [ ]:
# Arithmetic Operators

print(5 + 4)
print(2 * 3)
print(9.0 - 4.5)
print(6 % 4)    # modulo
print(5 // 2)   # integer division
print(5 / 2)    # float division
print(2 ** 3)   # exponentiation

9
6
4.5
2
2
2.5
8


In [ ]:
# Assignment Operators

x:int = 5
print(str(x))
x += 1
print(str(x))
# don't use x++

5
6


In [ ]:
# Logical Operators

x = True
y = False

print("x and y = {}".format(x and y))
print("x or y = {}".format(x or y))
print("not x = {}".format(not x))

x and y = False
x or y = True
not x = False


**Printing**

In [ ]:
y = 2
cat_1 = "Misty"
cat_2 = "Stormy"

# + is used for string concatenation
# must cast to string before printing to avoid errors
print("Taylor has " + str(y) + " cats, named " + cat_1 + " and " + cat_2 + ".")

Taylor has 2 cats, named Misty and Stormy.


**If/Else Statements**
Unlike some other programming languages, Python does not use braces ({}) to indicate blocks of code for class, function or flow control. Instead of braces, you will use line indentation, which is rigidly enforced. Try changing the indentation and fixing it below.

In [ ]:
x:int = int(input("Enter a number: "))

if x < 0:
  print("x is a negative number")
elif x == 0:
  print("x is zero")
else:
  print("x is a positive number")

Enter a number: 2
x is a positive number


**Range** ```range(start, step, end)``` is a function in Python that enables easy looping. There are three inputs: ```start``` (inclusive, optional, default: 0), ```step``` (optional, default: 1), ```end``` (exclusive, required).

In [ ]:
range1 = range(1, 11, 2)
range2 = range(6)

print("Range 1")
for i in range1:
  print(i)

print("Range 2")
for i in range2:
  print(i)

**Loops** The primary types of loops in Python are ```for``` loops and ```while``` loops. ```for``` loops have an initialization (```i``` in the example below) and a sequence (```range(0,5)``` in the example below).

In [ ]:
# For Loop
for i in range(0, 5):
    print(i)

```while``` loops repeatedly execute a block of code while the listed condition (```i > 0``` in the example below) is ```True```.

In [ ]:
# While Loop
i:int = 5
while i > 0:
    print(i)
    i -= 1

**Lists** Lists are ordered series of items. They are 0-indexed. You can also negative index from the end of a list (as show below). For example, indexing at ```-1``` is equivalent to the index ```n-1``` where ```n``` is the length of the list. You can use the ```len()``` function to get the length of a list.

In [ ]:
colors = ['red', 'green', 'blue', 'pink', 'purple']

first = colors[0]
second = colors[1]
last = colors[-1]
second_last = colors[-2]
length = len(colors)

print("first = {}".format(first))
print("second = {}".format(second))
print("last = {}".format(last))
print("second_last = {}".format(second_last))
print("length = {}".format(length))

**Lists: manipulation** You can also manipulate Python lists; we show some examples below.

In [ ]:
colors = ['red', 'green', 'blue', 'pink', 'purple']
print("colors = {}".format(colors))

#append an element to the end of the list
colors.append('orange')
print("\ncolors.append('orange'):\ncolors = {}".format(colors))

#insert an element at an index (here, insert 'yellow' at index 1)
colors.insert(1, 'yellow')
print("\ncolors.insert(1, 'yellow'):\ncolors = {}".format(colors))

#remove by value (will return error if value does not exist in the list)
colors.remove('red')
print("\ncolors.remove('red'):\ncolors = {}".format(colors))

#delete by position (here, the last index in the list)
del colors[-1]
print("\ndel colors[-1]:\ncolors = {}".format(colors))

#change an element at an index
colors[2] = 'indigo'
print("\ncolors[2] = 'indigo':\ncolors = {}".format(colors))

#adding returns a new list (vs append, which adds to the list 'in-place')
#definition: in-place operations modify the object directly
colors = colors + ['orange', 'yellow']
print("\ncolors = colors + ['orange', 'yellow']:\ncolors = {}".format(colors))

colors = ['red', 'green', 'blue', 'pink', 'purple']

colors.append('orange'):
colors = ['red', 'green', 'blue', 'pink', 'purple', 'orange']

colors.insert(1, 'yellow'):
colors = ['red', 'yellow', 'green', 'blue', 'pink', 'purple', 'orange']

colors.remove('red'):
colors = ['yellow', 'green', 'blue', 'pink', 'purple', 'orange']

del colors[-1]:
colors = ['yellow', 'green', 'blue', 'pink', 'purple']

colors[2] = 'indigo':
colors = ['yellow', 'green', 'indigo', 'pink', 'purple']

colors = colors + ['orange', 'yellow']:
colors = ['yellow', 'green', 'indigo', 'pink', 'purple', 'orange', 'yellow']


**Lists: slicing** You can also slice lists, which allows the extraction of sub-parts from a list. For slicing, you define the terms ```start``` (inclusive, optional, default = 0), ```stop``` (exclusive, optional, default = -1), and ```step``` (optional, default=1). ```step``` values can also be negative, enabling slicing in reverse.

In [ ]:
colors = ['red', 'green', 'blue', 'pink', 'purple']

#first three elements
print("colors[1:3] = {}".format(colors[1:3]))
#all but the first (0th) element
print("colors[1:] = {}".format(colors[1:]))
#up to and including the 3rd element (colors[2])
print("colors[:3] = {}".format(colors[:3]))
#the last two elements
print("colors[-2:] = {}".format(colors[-2:]))
#every other element starting at 0
print("colors[::2] = {}".format(colors[::2]))
#every other element starting at 1
print("colors[1::2] = {}".format(colors[1::2]))
#all elements
print("colors[:] = {}".format(colors[:]))
#all elements reversed
print("colors[::-1] = {}".format(colors[::-1]))


colors[1:3] = ['green', 'blue']
colors[1:] = ['green', 'blue', 'pink', 'purple']
colors[:3] = ['red', 'green', 'blue']
colors[-2:] = ['pink', 'purple']
colors[::2] = ['red', 'blue', 'purple']
colors[1::2] = ['green', 'pink']
colors[:] = ['red', 'green', 'blue', 'pink', 'purple']
colors[::-1] = ['purple', 'pink', 'blue', 'green', 'red']


**Generating lists** You can use list comprehension in Python to generate lists efficiently. The example below generates a list of squares, using the ```range()``` function as described above. We compare this to generating a list without list comprehension, which is valid but not as efficient.

In [ ]:
#Efficient method of generating list of squares from 1 - 10
squares_efficient = [x ** 2 for x in range(1, 11)]
print(squares_efficient)

#Inefficient method of generating list of squares from 1 - 10
squares_inefficient = []
for x in range(1, 11):
  square = x ** 2
  squares_inefficient.append(square)
print(squares_inefficient)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


**Strings continued** String manipulation and indexing uses a similar notation to lists (treated as a list of ```chars```). However, strings in Python are immutable, meaning you cannot change, add, or remove elements without creating a new object.

In [ ]:
x = "CSE D 501"

first = x[0]
length = len(x)
last = x[-1]
a = x[::2]

print("first = {}".format(first))
print("length = {}".format(length))
print("last = {}".format(last))
print("a = {}".format(a))

first = C
length = 9
last = 1
a = CED51


**Tuples** Tuples are also immutable, and are an ordered list of values. They can be indexed in the same way as lists.

In [ ]:
# Immutable ordered list of values

t = (2, 4, 6)

# Index the same way as lists
print("t[0] = {}".format(t[0]))
print("t[1] = {}".format(t[1]))
print("t[2] = {}".format(t[2]))

# A different way to get the values of tuples
a, b, c = (2, 4, 6)
print("a = {}".format(a))
print("b = {}".format(b))
print("c = {}".format(c))

**Imports** You can import libraries in Python, which provide functions, classes, and modules. We'll be using several of these throughout the course.

The ```math``` library can be useful for mathematical equations. Examples are shown below.

In [ ]:
#This imports the entire math module
import math

#math.sqrt() gives you access to the sqrt() function in the math library
x = math.sqrt(9)

print("x = {}".format(x))

In [ ]:
#This imports the entire math module aliased as m
import math as m

x = m.sqrt(9)

print("x = {}".format(x))

In [ ]:
#This only imports the sqrt function from the math module and no others
from math import sqrt

#Note that in this case you do not need to write math.sqrt(), as only the
#sqrt() function was imported
x = sqrt(9)

print("x = {}".format(x))

**Functions** Python functions are defined using the ```def``` keyword.

In [ ]:
# A Basic Function

#multiplier: the function name
#x, y: parameter names
# -> int: return type
def multiplier(x:int, y:int) -> int:
    return x * y

print(multiplier(4, 5))
print(multiplier(3, "hi")) # Typing not enforced!

Using keyword arguments as shown below lets you specify parameters for arguments, allowing you to bypass order.

In [ ]:
# Keyword Arguments

def divide(x:int, y:int) -> float:
  return y / x

print(divide(x = 9, y = 3))
print(divide(y = 3, x = 9))

Functions can also have default parameters. Default parameter values are used if no argument is supplied; if an argument is not supplied for a parameter value without a default, an error will occur. When using default parameters, they must come at the end of the function.

In [ ]:
# Default Parameters

def greet(name:str, greeting:str = "Hello"):
  print(greeting + " " + name)

greet("Bob")
greet(name="Bob")
greet(name="Bob", greeting="Good afternoon")
greet(greeting="What's up", name="Bob")

In Python, you can also pass functions as arguments to other functions. We show an example below.

In [ ]:
# Passing Functions

from typing import Callable

def add_lines(text_func:Callable):
  print('---------------')
  print(text_func())
  print('---------------')

def fact():
  return "the sky is blue"

add_lines(fact)

---------------
the sky is blue
---------------


We've only shown examples of returning single values so far, but in Python you can also return multiple return values. When doing so, they are returned as an implicit tuple.

In [ ]:
# Multiple Return Values

def func():
    return 'hello', 5

x,y = func()
for i in range(y):
    print(x)

**Helper functions** You can also define functions within other functions. Those ineer functions are only available in the scope of the outer function.

In [ ]:
# Helper Functions

import math as m

def getArea(radius):
  def square(r):
    return r**2
  return m.pi * square(radius)

print(getArea(1))
print(getArea(2))

3.141592653589793
12.566370614359172


In [ ]:
# This will produce an error, because the square() function is only
# defined within getArea()

print(square(5))

TypeError: 'int' object is not callable

**Main function** Python does not strictly require a function named main(), but one is often used for organizational purposes.

In [ ]:
# Main Method

def main():
    print("Hello")

# calls main method when this file is run with `python file_name.py` from the terminal
if __name__ == "__main__":
    main()

Hello


**Sets** Sets are collections of unique elements. An example of constructing and working with sets is shown below.

In [ ]:
x = set()
x.add(1) # {1}
print("x.add(1): x = {}".format(x))
x.add(3) # {1, 3}
print("x.add(3): x = {}".format(x))

# Alternate notation
y = {1, 3, 3} # {1, 3} - unique elements only
print("y = {{1, 3, 3}} means y = {}".format(y))

print("1 in x = {}".format(1 in x))
print("1 not in x = {}".format(1 not in x))
print("len(x) = {}".format(len(x)))
x.remove(1)
print("x.remove(1): x = {}".format(x))

x.add(1): x = {1}
x.add(3): x = {1, 3}
y = {1, 3, 3} means y = {1, 3}
1 in x = True
1 not in x = False
len(x) = 2
x.remove(1): x = {3}


**Dictionaries** Dictionaries are unordered collections of key/value mappings. Examples of working with dictionaries are shown below.

In [ ]:
x = {'Grace': 'H', 'Margaret':'Hamilton'}
print("x = {}".format(x))

x1 = x['Grace'] # Returns value associated with key, i.e. ‘H’
print("\nx['Grace'] = {}".format(x1))

x['Grace'] = 'Hopper' # Reassigns value associated with key
print("\nx = {}".format(x))

print('')

if 'Grace' in x.keys(): # Returns true if in keyset
  print('yup')

print('')

# Iterate through every key first_n in dictionary x
for first_n in x:
  print(first_n + " " + x[first_n])

x = {'Grace': 'H', 'Margaret': 'Hamilton'}

x['Grace'] = H

x = {'Grace': 'Hopper', 'Margaret': 'Hamilton'}

yup

Grace Hopper
Margaret Hamilton


**Classes** A class serves as a template for creating objects in python. Classes consist of data and functions. An example class is shown below.

In [ ]:
class Line:
  '''
  This class represents straight lines in slope-intercept form
  ax + b
  '''

  '''
  Constructor: defined with special __init__() function.
  Constructors are run when an object is created.
  self is a reference to the object itself, and must be explicitly
  passed as the first parameter to every function.
  '''
  def __init__(self, a, b):
    # Constructor

    #Fields are defined within the constructor
    self.a = a
    self.b = b

  def get_slope(self):
    #Fields can be accessed using self in any class functions
    return self.a

  def set_intercept(self, b):
    self.b = b


#This creates (instantiates) a instance of the Line class
#my_line is an object
#Note that "self" is only used within the class itself, not when the class
#is instantiated or when its functions are called
my_line = Line(5, 7)
print("my_line.a = {}".format(my_line.a))
print("my_line.b = {}".format(my_line.b))

print("")

#Function calls: object.function(parameters)
my_line.get_slope()
print("my_line.get_slope() = {}".format(my_line.get_slope()))

print("")

my_line.set_intercept(2)
print("my_line.a = {}".format(my_line.a))
print("my_line.b = {}".format(my_line.b))

#Very quick NumPy Tour

**NumPy is much faster and much more memory efficient than Python for arrays**

NumPy arrays are stored as contiguous blocks of memory with a fixed data type. Operations on arrays are implemented in optimized C code that works directly on these memory buffers. This eliminates the overhead of Python’s interpreter loop and makes use of fast, cache-friendly operations. Using NumPy to express array operations keeps the computation in these fast C loops rather than slow Python loops.

In NumPy, you can use *arrays*, powerful data structures that are a special type of list. Each item in the list can be of any type (ints, floats, strings, other arrays, etc). Arrays in NumPy are often created by transforming a regular Python list into an array in a new variable using ```np.array()```.

In [ ]:
#Importing the NumPy library. This is often aliased as np
import numpy as np

python_list = [1,2,3,4,5]
numpy_array = np.array(python_list)

print(python_list)
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


There are other ways of creating arrays in NumPy as well, which NumPy has many built-in functions for. Two such commonly-used functions are ```np.zeros(shape)``` and ```np.ones(shape)```, which create arrays with the specified shape filled with 0s and 1s respectively. For 1D arrays, ```shape``` is an integer; for multidimensional arrays, ```shape``` is a tuple. For created arrays, the shape of a NumPy array ```arr``` can be found with ```arr.shape```.

In [ ]:
#Importing the NumPy library. This is often aliased as np
import numpy as np

#Create a 1D array of size 3, all zeros
zeros = np.zeros(3)
print(zeros)
print(zeros.shape)

#Create a 2D array of size 2x3, all ones
ones = np.ones((2,3))
print(ones)
print(ones.shape)


[0. 0. 0.]
(3,)
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


**Element-wise operations** Numpy lets you do *element-wise operations*. Element-wise operations apply a function or operation to each element in an array.

Our first example of NumPy vs Python will be adding a number to every value in a Python list vs a NumPy array.

In [ ]:
#Importing the NumPy library. This is often aliased as np
import numpy as np

#Adding 5 to every element in a python list

python_list = [1,2,3,4,5]

for i in range(len(python_list)):
  python_list[i] += 5

print(python_list)

#Adding 5 to every element in a NumPy array
numpy_array = np.array([1,2,3,4,5])

numpy_array += 5

print(numpy_array)


[6, 7, 8, 9, 10]
[ 6  7  8  9 10]


Using element-wise operations in NumPy lets you add 5 to every element without using ```for``` loops or list comprehension, which NumPy can do efficiently. You can do many other arithmatic operations using NumPy's element-wise operations as well.

**Operations between NumPy arrays vs Python lists** NumPy arrays can be added and subtracted from each other if they have the same shape (or can be broadcast, which we'll cover later). When adding and subtracting arrays in NumPy, every element is add or subtracted from its matching element in the other array.

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

#These arrays have the same shape: 5 elements
print("Shape of a and b")
print(a.shape)
print(b.shape)

print("Adding NumPy arrays a and b")
print(a+b)

#Compare this to "adding" two Python lists
print("Adding Python lists c and d")
c = [1,2,3,4,5]
d = [6,7,8,9,10]
print(c+d)

Shape of a and b
(5,)
(5,)
Adding NumPy arrays a and b
[ 7  9 11 13 15]
Adding Python lists c and d
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**Matrices** In Python, we can create lists of lists as shown below.

In [ ]:
row0 = [1,2,3]
row1 = [4,5,6]
row2 = [7,8,9]
matrix = [row0, row1, row2]
print(matrix)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In NumPy, we can create arrays of arrays, and we can specifically create matrices. Below, we show an example of creating a 3x3 array with rows [1,2,3], [4,5,6], and [7,8,9].

In [ ]:
import numpy as np

#The outer [] are required; the code will not run without them
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Indexing** You can access elements in a NumPy array by index. When accessing from a 1D array, the syntax is identical to accessing the elements of a list in Python (NumPy arrays are 0-indexed); you can use ```array[index]``` or ```array[start:end:step]``` for a slice. As with Python lists, For slicing, you define the terms ```start``` (inclusive, optional, default = 0), ```stop``` (exclusive, optional, default = -1), and ```step``` (optional, default=1). ```step``` values can also be negative, enabling slicing in reverse.


In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])

#print the first element
print(a[0])
print("")

#print the last element
print(a[-1])
print("")

#print all elements except the first (0th index)
print(a[1:])
print("")

#print every other element starting with the first (0th index)
print(a[::2])
print("")

#print the second through fourth element
print(a[1:4])
print("")

1
5
[2 3 4 5]
[1 3 5]
[2 3 4]


With $n$-dimensional NumPy arrays, you can still index, and you have $n$ indices to select from. We'll show examples for 2D NumPy arrays, as most of the data you'll work with in this course will be in 2D arrays.

To select from a 2D array ```arr```, the syntax is ```arr[row,column]```. A 2D array has two *axes*: axis 0 and axis 1. Axis 0 represents columns, the values that share the same indexical position. Axis 1 represents rows, the values that share an array.

Besides integer indexing and slicing, you can also perform integer array indexing by passing a list/array of indices to grab multiple rows or columns at once.

In [ ]:
import numpy as np

a = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15]
    ]
)

#Select the element at row 2, column 1
print(a[1,0])
print("")

#A : selects an entire row or column
#Select the first column:
print(a[:,0])
print("")

#Select the third row:
print(a[2,:])
print("")

#Select the last two elements of the first row
print(a[0,-2:])
print("")

#integer array index rows 1 and 3
print(a[[0,2]])


6

[ 1  6 11]

[11 12 13 14 15]

[4 5]

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


**Reshaping** If you need to change the shape of an array, you can do so using the ```reshape()``` function. The new shape must have the same total number of elements or be otherwise compatible with the original shape (through NumPy broadcasting, for example, covered later on).

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
print(a)

print("")
b = a.reshape((2,4))
print(b)

print("")
c = b.reshape((4,2))
print(c)




[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Arrays and Logical Operations** NumPy can also perform element-wise *logical operations*, which work for any NumPy array of any shape. Below is an example of using an element-wise logical operation to select all elements in an array are greater than 10. We first create a *boolean mask* with the locations of elements > 10, a boolean-valued array that can be used to select elements from another array. We then apply the mask to our original array.

We also show an example of the  [```arange()```](https://numpy.org/doc/2.3/reference/generated/numpy.arange.html) function to generate an array.



In [ ]:
import numpy as np

a = np.arange(0,20,2)
print(a)

#Logical operations createa boolean mask
print(a > 10)

#We can apply the boolean mask to the original array
#Indexing with this logical operation selects only the elements > 10
print(a[a > 10])

#You can also use boolean operators (& (and), | (or), etc) to combine criteria
#Select elements > 4 and < 15
print(a[(a > 4) & (a < 15)])

[ 0  2  4  6  8 10 12 14 16 18]
[False False False False False False  True  True  True  True]
[12 14 16 18]
[ 6  8 10 12 14]


**Aggregators** Numpy provides aggregate functions that can summarize the data in arrays. We show a few examples of some of these aggregate functions below.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

#The original array
print(arr)

print("")

#The sum of all elements in the array
print(np.sum(arr))

print("")

#The sum along each column
print(np.sum(arr, axis=0))

print ("")

#The sum along each row
print(np.sum(arr, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

78

[15 18 21 24]

[10 26 42]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 7, 12],
                [5, 6, 11, 8],
                [9, 10, 3, 4]])

#The mean value of the array
print(np.mean(arr))

print("")

#The minimum value in each column
print(np.min(arr, axis=0))

print("")

#The maximum value in each row
print(np.max(arr, axis=1))

print("")

#The index of the maximum value in each row
print(np.argmax(arr, axis=1))

6.5

[1 2 3 4]

[12 11 10]

[3 2 1]


**In-place Operations**

NumPy also lets you modify arrays in place, meaning the original array is directly updated without creating a copy. This is efficient and often preferred when working with very large arrays. You can assign values or perform arithmetic operations in place using the indexing rules defined above and Python syntax. Other, more complex operations can also be performed in place, but we will not cover that here. For those interested: https://numpy.org/doc/2.1/reference/ufuncs.html

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])

#Modify the first entry in place
a[0] = 100
print(a)

#Add 5 in place to any values < 5
a[a<5] += 5
print(a)

[100   2   3   4   5]
[100   7   8   9   5]


**Shape Broadcasting**

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. The smaller array is "broadcast" across the larger array so that they have compatible shapes.

In [ ]:
import numpy as np

#Adding a scalar to an array is an example of broadcasting
#Here, the scalar 5 is broadcast to each element of arr to add 5 to every element
a = np.array([1,2,3,4,5])
print(a + 5)

print("")

#Another example is adding a single array of length 5
#to all rows of a 3x5 array
b = np.array([1,2,3,4,5])
c = np.array([
    [1,2,3,4,5],
    [5,4,3,2,1],
    [0,0,0,0,0]
])
print(b + c)


[ 6  7  8  9 10]

[[ 2  4  6  8 10]
 [ 6  6  6  6  6]
 [ 1  2  3  4  5]]


#NumPy Examples with larger arrays

To show these concepts with less toy arrays, we'll first create some data to work with. We'll generate two arrays, ```X``` and ```Y```. ```X``` will have dimensions $n_x$ by $d$, where $n_x = 100, d = 64$, and ```Y``` will have dimensions $n_y$ by $d$, where $n_y = 150, d = 64$. The entries of ```X``` and ```Y``` will be drawn from a standard Normal distribution (mean=0, stdev=1) using [```np.random.standard_normal```](https://numpy.org/doc/2.1/reference/random/generated/numpy.random.standard_normal.html).

In [ ]:
import numpy as np

rng = np.random.RandomState(seed=42)  # we set the random seed for reproducibility

nx, ny, d = 100, 150, 64

# generate data(each entry is sampled from a standard normal distribution N(0, 1))
X = rng.standard_normal((nx, d))
Y = rng.standard_normal((ny, d))

# print info about the arrays
print(X.shape, X.dtype, X.size)
print(Y.shape, Y.dtype, Y.size)

(100, 64) float64 6400
(150, 64) float64 9600


**Indexing examples**

For more details check: https://numpy.org/devdocs/user/basics.indexing.html. For example, although we will not cover it here, types of indexing can be combined.


- Slicing indexing

In [ ]:
print(X[:50].shape) # first 50 rows
print(X[:, -50:].shape) # last 50 columns
print(X[::2, ::2].shape) # every other row and every other column.
print(X[:, ::-1].shape) # flips the order of the columns(a negative step size goes through the array in the opposite direction)

(50, 64)
(100, 50)
(50, 32)
(100, 64)


- Integer Indexing

In [ ]:
print(X[0, 1].shape) # element at row 0, col 1. Preferred instead of X[0][1].
print(X[1].shape) # second row
print(X[:, 2].shape) # third column
print(X[-2, -1].shape) # last column from second to last row

()
(64,)
(100,)
()


- Integer Array Indexing

In [ ]:
print(X[[0, 2, 4]].shape) # rows 0, 2, 4
print(X[:, np.array([0, 8, 16, 24])].shape) # columns 0, 8, 16

(3, 64)
(100, 4)


- Mask Indexing

In [ ]:
# create an entrywise boolean mask which is True if the entry is >0.5 and False otherwise.
array_mask = X > 0.5
# get all entries in X greater than 0.5
# (note that the result array is flattened to a single row)
print(X[array_mask].shape)

# create a row boolean mask which is True if the mean along that row is >0.0 and False otherwise.
row_idx = X.mean(axis=1) > 0.0
# get all rows where the mean value across the row is greater than 0.
print(X[row_idx].shape)

# create a column boolean mask which is True if the max along that column is >3.0 (3 standard deviation away)and False otherwise.
col_idx = X.max(axis=0) > 3.0
# get all columns with the max along that column >3.0
print(X[:, col_idx].shape)

(1956,)
(52, 64)
(100, 10)


**In-place Operations**

In [ ]:
# Pick the first 5 rows and 5 cols of X.
X_small = X[:5, :5]

print("----Modify top left entry----")
X_copy = X_small.copy() #copy() creates a new, independent array with its own memory
print("Before:\n", X_copy)
X_copy[0, 0] = 99
print("After:\n", X_copy, "\n")

print("----Modify bottom right entry----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy[-1, -1] = np.inf
print("After:\n", X_copy, "\n")

----Modify top left entry----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]]
After:
 [[ 9.90000000e+01 -1.38264301e-01  6.47688538e-01  1.52302986e+00
  -2.34153375e-01]
 [ 8.12525822e-01  1.35624003e+00 -7.20101216e-02  1.00353290e+00
   3.61636025e-01]
 [ 9.96513651e-02 -5.03475654e-01 -1.55066343e+00  6.85629748e-02
  -1.06230371e+00]
 [ 2.14093744e-01 -1.24573878e+00  1.73180926e-01  3.85317380e-01
  -8.83857436e-01]
 [ 1.26691115e+00 -7.07669466e-01  4.43819428e-01  7.74634053e-01
  -9.26930472e-01]] 

----Modify bottom right entry----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0

- Modify whole rows/cols

In [ ]:
print("----Modify the whole second row----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy[1] = round(np.pi, 2) # set to 3.14
print("After:\n", X_copy, "\n")

print("----Modify the whole last column----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy[:, -1] = round(np.e, 2) # set to 2.72
print("After:\n", X_copy, "\n")

print("----Vector assignment: place values on the first row----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
# assign different values per row.
# note that numpy automatically casts the integer array on the RHS to floats
X_copy[0] = np.array([-2, -1, 0, 1, 2])
print("After:\n", X_copy, "\n")

print("----Vector assignment: place values on the last column----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy[:, -1] = np.array([-2, -1, 0, 1, 2])
print("After:\n", X_copy, "\n")

----Modify the whole second row----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]]
After:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 3.14        3.14        3.14        3.14        3.14      ]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]] 

----Modify the whole last column----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -

- Modify Blocks

In [ ]:
print("----Matrix assignment: replace the top left block----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy[:2, :2] = np.array([[1, 0], [0, 1]])  # replace top-left 2x2 block
print("After:\n", X_copy, "\n")

----Matrix assignment: replace the top left block----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]]
After:
 [[ 1.          0.          0.64768854  1.52302986 -0.23415337]
 [ 0.          1.         -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]] 



- Conditional Modifications

In [ ]:
print("----Conditional Replacement: truncate values----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy[X_copy < 0.2] = 0  # set values smaller that 0.2 to 0
X_copy[X_copy > 0.8] = 1  # set values greater that 0.8 to 0
print("After:\n", X_copy, "\n")

----Conditional Replacement: truncate values----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]]
After:
 [[0.49671415 0.         0.64768854 1.         0.        ]
 [1.         1.         0.         1.         0.36163603]
 [0.         0.         0.         0.         0.        ]
 [0.21409374 0.         0.         0.38531738 0.        ]
 [1.         0.         0.44381943 0.77463405 0.        ]] 



- In-place arithmetic

In [ ]:
print("----Arithmetic in place: Adding----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy[:2] += 5  # add 5 to the first two rows
print("After:\n", X_copy, "\n")

print("----Arithmetic in place: Squaring----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy **= 2  # square the whole thing
print("After:\n", X_copy, "\n")

print("----Arithmetic in place: Divide by col standard deviation ----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
X_copy /= X_copy.std()   # standardize
print("After:\n", X_copy, "\n")

----Arithmetic in place: Adding----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]]
After:
 [[ 5.49671415  4.8617357   5.64768854  6.52302986  4.76584663]
 [ 5.81252582  6.35624003  4.92798988  6.0035329   5.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]] 

----Arithmetic in place: Squaring----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 

- Advanced: Other Operations in-place

In [ ]:
print("----Advanced: exp in-place----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
# apply exponential directly in memory
# if "out=X_copy" not supplied, exp() will default to creating a new array
np.exp(X_copy, out=X_copy)
print("After:\n", X_copy, "\n")

print("----Advanced: sin in-place----")
X_copy = X_small.copy()
print("Before:\n", X_copy)
np.sin(X_copy, out=X_copy)  # apply sin directly in memory
print("After:\n", X_copy, "\n")


----Advanced: exp in-place----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]]
After:
 [[1.64331272 0.87086849 1.91111824 4.58609939 0.79124045]
 [2.25359298 3.88157123 0.93052148 2.72790222 1.4356763 ]
 [1.10478568 0.60442623 0.21210721 1.07096807 0.34565859]
 [1.23873877 0.28772826 1.18908122 1.47008082 0.413186  ]
 [3.54987059 0.49279133 1.55864901 2.16979795 0.39576666]] 

----Advanced: sin in-place----
Before:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -

**Shape Broadcasting**  Let's demonstrate broadcasting with our data arrays X and Y

Add a vector (e.g., the first row of X) to all rows of Y

In [ ]:
print("Adding first vector in X to all vectors in Y:\n")

first_row_X = X[0] # shape (d,)
# numpy automatically broadcasts `first_row_X` to shape (1, d)
sum_XY = first_row_X + Y # shape (ny, d)

# Display only the first 5 rows and 5 cols for brevity
print(f"Y={Y[:5, :5]}\n")
print(f"X_0={first_row_X[:5]}\n")
print(f"sum_XY={sum_XY[:5, :5]}\n")

Adding first vector in X to all vectors in Y:

Y=[[ 0.33011379 -0.81401067 -0.36567708  0.50427075  0.5214494 ]
 [-1.20775939  0.80911279 -0.84972092 -0.48298393  0.53068312]
 [ 0.01959962 -0.80243004  0.57892865  0.46004232  1.54044124]
 [ 1.46978426 -0.62227022 -1.84026638  1.32816605 -0.50429802]
 [-1.26929111  1.53615677 -0.11131885  0.29908573  0.83315777]]

X_0=[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]

sum_XY=[[ 0.82682794 -0.95227497  0.28201146  2.0273006   0.28729602]
 [-0.71104524  0.67084849 -0.20203238  1.04004593  0.29652975]
 [ 0.51631377 -0.94069434  1.22661719  1.98307218  1.30628787]
 [ 1.96649841 -0.76053452 -1.19257785  2.85119591 -0.73845139]
 [-0.77257695  1.39789247  0.53636969  1.82211559  0.59900439]]



- Divide all rows of X by their norms (calculated using [```numpy.linalg.norm```](https://numpy.org/doc/2.3/reference/generated/numpy.linalg.norm.html))

In [ ]:
print("Broadcasting row lengths across columns of X and dividing X by its row lengths):\n")

X_norms = np.linalg.norm(X, axis=1) # shape (nx,)

# To broadcast X_norms across the columns of X, we need to reshape it to (nx, 1)
X_norms_reshaped = X_norms.reshape(nx, 1) # shape (nx, 1)
divided_X = X / X_norms_reshaped # shape (nx, d)

# Display only the first 5 rows and 5 cols for brevity
print(f"X={X[:5, :5]}\n")
print(f"X_norms_reshaped={X_norms_reshaped[:5]}\n")
print(f"Divided_X={divided_X[:5, :5]}\n")

Broadcasting row lengths across columns of X and dividing X by its row lengths):

X=[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603]
 [ 0.09965137 -0.50347565 -1.55066343  0.06856297 -1.06230371]
 [ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744]
 [ 1.26691115 -0.70766947  0.44381943  0.77463405 -0.92693047]]

X_norms_reshaped=[[7.28376797]
 [7.83696682]
 [7.37951572]
 [8.60228835]
 [7.48054208]]

Divided_X=[[ 0.06819467 -0.01898252  0.08892218  0.20909917 -0.03214729]
 [ 0.10367861  0.17305675 -0.00918852  0.12805119  0.0461449 ]
 [ 0.01350378 -0.06822611 -0.21013079  0.00929099 -0.14395304]
 [ 0.024888   -0.14481481  0.02013196  0.04479243 -0.10274678]
 [ 0.16936087 -0.09460136  0.05932985  0.1035532  -0.12391221]]



- Shape manipulation routines for X and Y

In [ ]:
# np.reshape: Gives a new shape to an array without changing its data.
# np.reshape with -1: Reshapes the array into one dimension using -1.
# The -1 tells NumPy to infer the length of that dimension based on the size of the array.

# Reshape X into a 3D array
print(f"Original X shape: {X.shape}")
X_reshaped = np.reshape(X, (nx, 1, d))
print(f"Reshaped X shape: {X_reshaped.shape}")

# Flatten X into a 1D array
X_flattened = np.reshape(X, -1) # shape (nx * d,)
print(f"Flattened X using reshape with -1 shape: {X_flattened.shape}")

# We could also reshape X or Y to a 3D arrays without adding only a dimension of length 1
# For example, we could transform every point in Y to an (8, 8) array.
# Any shape is fair game as long as the size of the array stays the same

print(f"Original Y shape: {Y.shape}")
Y_reshaped = np.reshape(Y, (ny, 8, 8)) # Reshape Y into a 3D array
print(f"Reshaped Y shape: {Y_reshaped.shape}\n")

Original X shape: (100, 64)
Reshaped X shape: (100, 1, 64)
Flattened X using reshape with -1 shape: (6400,)
Original Y shape: (150, 64)
Reshaped Y shape: (150, 8, 8)



- Space inefficient Euclidean distance calculation: Below we have a very space inefficient Euclidean distance calculation that leverages shape broadcasting by reshaping X and Y. This is memory inefficient because it creates large intermediate arrays, but it is fast.

In [ ]:
print("Space Inefficient Euclidean distance calculation using broadcasting:")

X_reshaped = np.reshape(X, (nx, 1, d))
Y_reshaped = np.reshape(Y, (1, ny, d))

# The difference will be broadcast to shape (nx, ny, d).
# Each entry diff[i, j, k] will store the difference between X[i, k] - Y[j, k]
diff = X_reshaped - Y_reshaped

print(f"Difference terms shapes: X.shape = {X_reshaped.shape}, Y.shape = {Y_reshaped.shape}")
print(f"Difference shape after broadcasting: {diff.shape}")

# The squared differences will also be shape (nx, ny, d)
diff_sq = diff ** 2
print(f"Squared difference shape: {diff_sq.shape}")

# Summing over the last axis (d) gives the squared Euclidean distances, shape (nx, ny)
D_sq = np.sum(diff_sq, axis=-1) # shape (nx, ny)
print(f"Squared Euclidean distance matrix shape: {D_sq.shape}")

# Taking the square root gives the Euclidean distances, shape (nx, ny)
D = np.sqrt(D_sq) # shape (nx, ny)
print(f"Resulting distance matrix shape: {D_sq.shape}")