
# Basic Math and Statistics


In [1]:
#Imports
import numpy as np
from numpy.random import randn

In [2]:
# Let's limit the number of decimal places returned by calling the set print options function and passing in the argument precision
np.set_printoptions(precision=2)

## Creating arrays
### Creating arrays using a list

In [3]:
#we'll create an array a here. Call the array constructor and then pass in a list of six values 
a = np.array([1,2,3,4,5,6])
#print that out and see what it looks like.
a

array([1, 2, 3, 4, 5, 6])

In [4]:
#Create a matrix b
b = np.array([[10,20,30], [40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
#Another way of creating an array via assignment
np.random.seed(11)
c = np.random.randn(6)
c

array([ 1.75, -0.29, -0.48, -2.65, -0.01, -0.32])

## Performing arthimetic on arrays

In [6]:
a * 10

array([10, 20, 30, 40, 50, 60])

In [7]:
c + a

array([2.75, 1.71, 2.52, 1.35, 4.99, 5.68])

In [8]:
c - a

array([ 0.75, -2.29, -3.48, -6.65, -5.01, -6.32])

In [9]:
c * a

array([  1.75,  -0.57,  -1.45, -10.61,  -0.04,  -1.92])

In [10]:
c / a

array([ 1.75e+00, -1.43e-01, -1.62e-01, -6.63e-01, -1.66e-03, -5.33e-02])

 I also want to show you about multiplying matrices and matrix multiplication.

So let's just create some objects we can use. We'll say np dot array to generate an array and then let's make three rows and three columns. The first row is going to have a value of two, four and six. And then in the second row you're going to have a one, a three and a five. And then in the third row you'll have a 10, a 20 and a 30.

### Multiplying matrices and basic linear algebra

In [11]:
aa = np.array([[2.,4.,6.], [1.,3.,5.], [10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [12]:
bb = np.array([[0.,1.,2.], [3.,4.,5.], [6.,7.,8.]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Arithmetic multiplication of two matrices works just like regular multiplication. So, in Python you can multiply these two matrices simply by writing aa times bb. And as you'll see here what's really happened is that the value in the first row and column of each of the matrices has been multiplied together and then four has been multiplied by one, so it returns a four. And then the third element in the first row those are multiplied together, so six times two is twelve.  This is different than dot product and formal matrix multiplication. 

In [13]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

We'll just call the dot function and then we'll pass in our two matrix objects, which is a way faster operation. Just to really quickly go over the procedure for matrix multiplication, you can see here that the first row is multiplied by the first column of the second matrix. When multiplied out and added together these values all add up to 48. Then for the second step, you would multiply the first row in the first matrix by the second column in the second matrix and so on.

In [14]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])